### ISSUE TITLE
How to set UART Mode to Midi/TCP?

### ISSUE THREAD

**Issue by neutralinsomniac** [bbond007/MiSTer_MidiLink#6]
I used to be able to connect to the net with the C64 core by changing the UART mode to MIDI/TCP. I updated this core today, and now that setting is gone. Choosing "Modem" actually ends up selecting "None", and "PPP" doesn't allow me to communicate with the modem either. Is there a new way to do TCP modem stuff with this core now?

**Comment by neutralinsomniac** [comment]
heh. Looks like this is a MiSTer_Main OSD issue. Closing.

**Comment by bbond007** [comment]
At the moment, the OSD is out of sync with the SD image...

You can wait for a new SD image to drop or get files here -->
https://misterfpga.org/viewtopic.php?p=18109#p18109

**Comment by neutralinsomniac** [comment]
Works flawlessly! Thank you!!
